#!/bin/sh
#
# Nagios plugin to monitor Java JMX (http://java.sun.com/jmx)attributes.
#
#RDIR=`dirname $0`
#$JAVA_HOME/bin/java  -cp $RDIR/jmxquery.jar jmxquery.JMXQuery $@
export JAVA_HOME=/srv/java

# resolve links, $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG="`dirname "$PRG"`/$link"
    fi
done

saveddir=`pwd`
RDIR=`dirname "$PRG"`
# make it fully qualified
RDIR=`cd "$RDIR" && pwd`
cd "$saveddir"

/srv/java/bin/java  -cp $RDIR/jmxquery.jar jmxquery.JMXQuery "$@"
